# 公共配置文件
spring:
  application:
    name: lantu-client-sdk
  # 默认 dev 环境
  profiles:
    active: dev
server:
  address: 0.0.0.0
  port: 8081
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
